### ISSUE TITLE
crash when use prefetto in android 10

### ISSUE THREAD

**Issue by jenics** [catapult-project/perfetto#3]
I meet a problem when use prefetto in android 10
device: Pixel XL
version: Android 10 (QP1A.191005.007.A1)
the error msg is shown below:

pprof_builder.cc:245     WARNING: The profile for 22029 was rejected due to a concurrent profile.
pprof_builder.cc:245     WARNING: The profile for 22029 was rejected due to a concurrent profile.
utils.cc:58              PERFETTO_CHECK(preamble == 0x0a) (errno: 0, Undefined error: 0)

------------------ BEGINNING OF CRASH ------------------
Signal: Illegal instruction (possibly unaligned access)
Fault addr: 0000000108D5C24F

Backtrace:

#00  _sigtramp

#01  perfetto::trace_to_text::ForEachPacketBlobInTrace(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::function<void (std::__1::unique_ptr<char [], std::__1::default_delete<char []> >, unsigned long)> const&)

#02  perfetto::trace_to_text::ForEachPacketInTrace(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::function<void (perfetto::protos::TracePacket const&)> const&)

#03  bool perfetto::trace_to_text::VisitCompletePacket<perfetto::trace_to_text::TraceToPprof(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::vector<perfetto::trace_to_text::SerializedProfile, std::__1::allocator<perfetto::trace_to_text:

#04  perfetto::trace_to_text::TraceToPprof(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::vector<perfetto::trace_to_text::SerializedProfile, std::__1::allocator<perfetto::trace_to_text::SerializedProfile> >*, perfetto::trace_to_text::S

#05  perfetto::trace_to_text::TraceToProfile(std::__1::basic_istream<char, std::__1::char_traits<char> >*, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)

#06  main
------------------ END OF CRASH ------------------
Traceback (most recent call last):
  File "heap_profile.py", line 408, in <module>
    sys.exit(main(sys.argv))
  File "heap_profile.py", line 373, in main
    [trace_to_text_binary, 'profile', '/tmp/profile'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/var/folders/34/4k9r7mps39d25z3vsy23v0r0chk970/T/trace_to_text-mac-47045bc6abd4f9113969211f37fdd2259b0c1cc3', 'profile', '/tmp/profile']' returned non-zero exit status -4

**Comment by fmayer** [comment]
Hey!

Thanks for getting in touch! Sorry to hear you are having problems. Did this happen once, or does this happen all the time?

Were you trying to run two profiles at the same time (as the output of pprof_builder.cc suggests)?

Could you send the output of `git show-ref HEAD` of the repository you are getting the tools/heap_profile from? Alternatively, could you attach the version of the script you are using?

Which process are you targeting?

**Comment by jenics** [comment]
@segfaulthunter 
Thanks to your replay.
your suggestion has helped me a lot.
I check my heap_profile version, the source of the tool is https://docs.perfetto.dev/#/heapprofd, the document indicate me to use the latest version"On Linux / MacOS, use the tools/heap_profile script to heap profile a process. If you are having trouble make sure you are using the latest version."
the latest version  is "https://raw.githubusercontent.com/catapult-project/perfetto/master/tools/heap_profile"
it doesn't work.
i checkout android10-c2f2-release and it works.
but, it i still having some trouble with it.

the msg is showing below:
You may disconnect your device.
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
utils.cc:89              Skipping invalid packet
Wrote profiles to /var/folders/34/4k9r7mps39d25z3vsy23v0r0chk970/T//heap_profile-t24iaWZ (symlink /var/folders/34/4k9r7mps39d25z3vsy23v0r0chk970/T/heap_profile-latest)
These can be viewed using pprof. Googlers: head to pprof/ and upload them.

----------------------------android studio log is shown below----------------------
2019-10-29 02:58:17.410 19563-19562/? I/perfetto: client.cc:257 Detected post-fork child situation, stopping profiling.
2019-10-29 02:58:33.262 19256-19256/? I/perfetto: perfetto_cmd.cc:815 SIGINT/SIGTERM received: disabling tracing.
2019-10-29 02:58:33.264 19441-19441/? I/perfetto: heapprofd_producer.cc:515 Data source not found (harmless if using continuous_dump_config).
2019-10-29 02:59:03.268 19256-19256/? E/perfetto: perfetto_cmd.cc:819 Final flush unsuccessful.
2019-10-29 02:59:03.271 767-767/? I/perfetto: probes_producer.cc:314 Producer stop (id=92)
2019-10-29 02:59:03.279 19256-19256/? I/perfetto: perfetto_cmd.cc:677 Wrote 705536 bytes into /data/misc/perfetto-traces/profile-shell
2019-10-29 02:59:03.330 764-764/? I/perfetto: tracing_service_impl.cc:1660 Tracing session 14 ended, total sessions:3

I use the Perfetto UI open the heap_profile ,it seems like no data had been shown.
the size is 105B, and I try so many times, every file is 105B.

**Comment by fmayer** [comment]
Thanks!

Would it be possible for you to pull and attach the file `/data/misc/perfetto-traces/profile-shell` from your phone? It contains 700K so there should be some data. It could help me determine what's going wrong.

Could you give me the exact command you are running? Could you run `adb shell getprop ro.vendor.build.fingerprint` and give me the output?
